/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bubble: typeof import('./src/components/Bubble/Bubble.vue')['default']
    Chatlist: typeof import('./src/components/Chatlist/Chatlist.vue')['default']
    ChatlistChat: typeof import('./src/components/ChatlistChat/ChatlistChat.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    MessageBubble: typeof import('./src/components/MessageBubble/MessageBubble.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserAvatar: typeof import('./src/components/UserAvatar/UserAvatar.vue')['default']
  }
}
