/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bubble: typeof import('./src/components/Bubble/Bubble.vue')['default']
    Chatlist: typeof import('./src/components/Chatlist/Chatlist.vue')['default']
    ChatlistChat: typeof import('./src/components/ChatlistChat/ChatlistChat.vue')['default']
    ChatlistHeader: typeof import('./src/components/ChatlistHeader/ChatlistHeader.vue')['default']
    Collapse: typeof import('./src/components/Collapse/Collapse.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    FriendMessageCount: typeof import('./src/components/ChatlistHeader/FriendMessageCount.vue')['default']
    GroupMessageCount: typeof import('./src/components/ChatlistHeader/GroupMessageCount.vue')['default']
    Image: typeof import('./src/components/Image/Image.vue')['default']
    MessageBubble: typeof import('./src/components/MessageBubble/MessageBubble.vue')['default']
    MessageCount: typeof import('./src/components/ChatlistHeader/MessageCount.vue')['default']
    Messagelist: typeof import('./src/components/Messagelist/Messagelist.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchMessage: typeof import('./src/components/SearchMessage/SearchMessage.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar/UserAvatar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
